server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://database-1.c16a4sk2iwmr.ap-northeast-2.rds.amazonaws.com:3306/projectdb
    driver-className: com.mysql.cj.jdbc.Driver
    userName: admin
    password: master2024

  jpa:
    database: mysql
    show:
      sql: true

jwt:
  secret: B6C899641631289237CFEB5C9F6629CB04A12A1FD2910A51A0E0544134BDC6AC

weather:
  key: cab8a38e7e6dd8318966f39499350716

logging:
  level:
    org.hibernate.SQL: debug