server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: ${DATABASE_URL}
    driver-className: com.mysql.cj.jdbc.Driver
    userName: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    database: mysql
    show:
      sql: true

jwt:
  secret: ${JWT_SECRET}

weather:
  key: ${WEATHER_KEY}

amazon:
  aws:
    accessKey: ${AWS_BUCKET_ACCESS_KEY}
    secretKey: ${AWS_BUCKET_SECRET_KEY}
    region: ap-northeast-2
    bucket: diary-image-bucket

logging:
  level:
    org.hibernate.SQL: debug