server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project?serverTimezone=UTC&characterEncoding=UTF-8
    driver-className: com.mysql.cj.jdbc.Driver
    userName: root
    password: 200356family

  jpa:
    database: mysql


logging:
  level:
    org.hibernate.SQL: debug